name: python pipeline

on: push

jobs:
  test: 
    run-on: ubuntu-latest
    steps:
      - uses: action/checkout@v2
      - run: python hello.py
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: action/checkout@v2
      - uses: action/upload-artifact@v2
        with:
          name: hello
          path: .
